### ISSUE TITLE
a few fixes

### ISSUE THREAD

**Issue by jvcasillas** [Kgeovanni/presentation#1]
try reknitting the presentation and see if it works now

**Comment by Kgeovanni** [comment]
I just want to make sure that I understand. The presentation knits on R. Do
you want me to try to reknit on Github?

Thank you for your assistance.
-----------------------------------------------
Diana Sánchez
Ph.D. Student
Department of Spanish & Portuguese
Bilingualism & Second Language Acquisition
*Zoom PMI: *370 680 6476
*Zoom Link:* https://rutgers.zoom.us/my/ds1731


INTERNET EMAIL CONFIDENTIALITY NOTICE:
The comments on and/or attachment to this e-mail are intended only for the
use of the individual or entity to which it is addressed, and may contain
information that is privileged, confidential and exempt from disclosure
under applicable law.  If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. If you received this
in error, please contact the sender immediately and delete the original
message, any attachment(s) and copies.
Thank you for your cooperation.
